#!/usr/bin/env python3
from markdown import markdown
from os import listdir as ls
from os import chdir as cd
from os.path import isfile as is_file
from os.path import isdir as is_dir
from os.path import join as joinp
from sys import argv
from sys import setrecursionlimit
setrecursionlimit(10**9)

def is_md(pathorname: str):
    return is_file(pathorname) and pathorname.endswith(".md")

def parse_md_file(path: str):
    with open(path, "rt") as file:
        return markdown(file.read().strip())

content = ''
def parse_dir(path):
    global content
    rootall = ls(path)
    for rootnode in rootall:
        rootnode = joinp(path, rootnode)
        if is_md(rootnode):
            content = content + parse_md_file(rootnode)
        elif is_dir(rootnode):
            content = content + parse_dir(rootnode)
        else:
            pass
    return content

def main():
    print(parse_dir(argv[1]))

if __name__ == "__main__":
    main()
