#!/usr/bin/env python3
import os
import sys

default_sink = os.popen("pamixer --get-default-sink").readlines()[1].rstrip().split('"')[1]
cmd = sys.argv[1]
if cmd == 'g':
    print(default_sink)

elif cmd == 't':
    sinks = [] 
    for x in range(2):
        sinks.append(os.popen("pamixer --list-sinks").readlines()[x+1].rstrip().split('"')[1])
    sinks.remove(default_sink)
    os.system("pactl set-default-sink {}".format(sinks[0]))



