#!/bin/bash
dmenu=dmenu-wl

walldir="$HOME/bg/"
maxpage=5
tagoptions="#gay\n#minimalism\n#Sexy Boy\n#fantasy boy\n#digital art\n#Hot Boy\n#Hunk"
if [ -z $1 ]; then
  query=$(echo -e $tagoptions | $dmenu -p "Search Wallhaven: " -i)  
else
  query=$1
fi

sortoptions="date_added\nrelevance\nrandom\nviews\nfavorites\ntoplist"
sorting=$(echo -e $sortoptions | $dmenu -p "Sort Order: " -i)

query="$(sed 's/#//g' <<<$query)"
query="$(sed 's/ /+/g' <<<$query)" 
echo $query

notify-send "⬇️ Downloading wallpapers 🖼️"
for i in $(seq 1 5);
do
  curl -s https://wallhaven.cc/api/v1/search\?atleast\=1920x1080\&sorting\=$sorting\&q\=$query\&page\=$i > tmp.txt
  page=$(cat tmp.txt | jq '.' | grep -Eoh "https:\/\/w\.wallhaven.cc\/full\/.*(jpg|png)\b")
  wget -nc -P $walldir $page
done
rm tmp.txt
notify-send "😊 Download finish ✅"
